-- Complete the schema that was historically generated by Hibernate ddl-auto=update.
-- Keeping these definitions in Flyway makes a clean database reproducible.

CREATE TABLE IF NOT EXISTS clinic_settings (
    id BIGSERIAL PRIMARY KEY,
    clinic_name VARCHAR(255),
    short_name VARCHAR(255),
    logo_url VARCHAR(255),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(255),
    address VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    specialty VARCHAR(255)
);

ALTER TABLE clinic_settings ADD COLUMN IF NOT EXISTS clinic_name VARCHAR(255);
ALTER TABLE clinic_settings ADD COLUMN IF NOT EXISTS short_name VARCHAR(255);
ALTER TABLE clinic_settings ADD COLUMN IF NOT EXISTS logo_url VARCHAR(255);
ALTER TABLE clinic_settings ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255);
ALTER TABLE clinic_settings ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(255);
ALTER TABLE clinic_settings ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE clinic_settings ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE clinic_settings ADD COLUMN IF NOT EXISTS specialty VARCHAR(255);

ALTER TABLE clinical_services ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE clinical_services ADD COLUMN IF NOT EXISTS description VARCHAR(500);
ALTER TABLE clinical_services ADD COLUMN IF NOT EXISTS price NUMERIC(10, 2) NOT NULL DEFAULT 0;
ALTER TABLE clinical_services ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE clinical_services ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE supplies ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE supplies ADD COLUMN IF NOT EXISTS description VARCHAR(500);
ALTER TABLE supplies ADD COLUMN IF NOT EXISTS current_stock INTEGER NOT NULL DEFAULT 0;
ALTER TABLE supplies ADD COLUMN IF NOT EXISTS min_stock_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE supplies ADD COLUMN IF NOT EXISTS unit VARCHAR(255);
ALTER TABLE supplies ADD COLUMN IF NOT EXISTS price NUMERIC(10, 2);
ALTER TABLE supplies ADD COLUMN IF NOT EXISTS expiration_date DATE;
ALTER TABLE supplies ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE supplies ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS psychometric_tests (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    questions_json TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS assessments (
    id BIGSERIAL PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    psychometric_test_id BIGINT NOT NULL,
    assessment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_score INTEGER,
    answers_json TEXT NOT NULL,
    notes TEXT,
    CONSTRAINT fk_assessments_patient
        FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    CONSTRAINT fk_assessments_psychometric_test
        FOREIGN KEY (psychometric_test_id) REFERENCES psychometric_tests(id)
);

CREATE TABLE IF NOT EXISTS inventory_transactions (
    id BIGSERIAL PRIMARY KEY,
    supply_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    transaction_type VARCHAR(255) NOT NULL,
    transaction_reason VARCHAR(255) NOT NULL,
    reference_id VARCHAR(255),
    notes VARCHAR(255),
    transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_transactions_supply
        FOREIGN KEY (supply_id) REFERENCES supplies(id)
);

CREATE TABLE IF NOT EXISTS payment_items (
    id BIGSERIAL PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL,
    supply_id BIGINT,
    clinical_service_id BIGINT,
    CONSTRAINT fk_payment_items_payment
        FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_items_supply
        FOREIGN KEY (supply_id) REFERENCES supplies(id),
    CONSTRAINT fk_payment_items_clinical_service
        FOREIGN KEY (clinical_service_id) REFERENCES clinical_services(id)
);

CREATE INDEX IF NOT EXISTS idx_assessments_patient_id ON assessments(patient_id);
CREATE INDEX IF NOT EXISTS idx_assessments_psychometric_test_id ON assessments(psychometric_test_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_supply_id ON inventory_transactions(supply_id);
CREATE INDEX IF NOT EXISTS idx_payment_items_payment_id ON payment_items(payment_id);
